### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by thhck** [asr-enid/fedcm-rp-node#1]
Hello, 

On debian running Chromium 120.0.6049.0, with the `fedcm` chrome flag set to `enable` I get the following error on localhost:7080:

![image](https://github.com/asr-enid/fedcm-rp-node/assets/133600193/0165da83-4195-445a-a66c-005a9a3a4e4c)

It is possible to make in run on linux too ?

**Comment by asr-enid** [comment]
There was a breaking change to the IDP API in 120 Canary, in order to work you need to use the latest patch merged yesterday in the IDP implementation: https://github.com/asr-enid/fedcm-idp-typescript

**Comment by asr-enid** [comment]
Sorry, the screenshot suggest FedCM is generally not yet supported on Chromium Linux. Thats unfortunately nothing I can help with, using Chrome should work though

**Comment by thhck** [comment]
Ok, 
I was not able to run with chrome 117 and canary isn't available for linux. So I there is now way to run this demo on linux for now. 

However the demo at https://fedcm-rp-demo.glitch.me/ works with latest version of chromium, are they relying on different browser api ?

**Comment by asr-enid** [comment]
Hmm that is not to be expected - I just tried with Chromium Version 120.0.6049.0 (Developer Build) (x86_64) with not flags set and it works without a problem

**Comment by asr-enid** [comment]
But on MacOS

**Comment by asr-enid** [comment]
@thhck is the above a screenshot? In case it is the setup does not seem to be properly setup (modules missing etc.) Did you follow the steps to setup the RP properly? https://github.com/asr-enid/fedcm-rp-node#getting-started

**Comment by thhck** [comment]
Could make it work with cleaning the cache and rebuilding it with npm, not sure what went wrong.
